name: Docker Hub for Server

on:
  push:
    branches:
      - "server"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Prepare source code
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize submodules
        run: |
          git submodule update --init

      # Prepare environment
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build and publish
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_USER }}/iperf3-server:latest
